### ISSUE TITLE
Does not create a new index for each new day.

### ISSUE THREAD

**Issue by owenhaynes** [sohlich/elogrus#3]
At the moment all logs are stored as the same index. 

Be better to create a new index for each day.

**Comment by alastairs** [comment]
Has there been any progress on this issue?

**Comment by sohlich** [comment]
How about this more flexible approach.[here](https://github.com/sohlich/elogrus/commit/b155b5c32534f737362ee1879f9d7d2c0047ff5b)

The intention here is to be more flexible in providing the index name. (see *NewElasticHookWithFunc*)

I didn't have a time to test it more yet, but this should work.

**Comment by jesseolsen** [comment]
Looks like I can implement this with "NewElasticHookWithFunc()", but would be nice to have a "NewElasticHookWithDateFormat(client, host, level, indexFormatString)" where indexFormatString is a string passed to time.Format().  For example, if the string was "logstash-2006.01.02", this would be passed to time.Format() each time a message is logged, so that it would be sent to the right index, no matter what day it was sent.  (We have other processes to clean up old indices, though others might want a cleanup function option...).

That would clean up what I am doing now:
```
   elasticHook, err = elogrus.NewElasticHookWithFunc(
              client, elasticsearchHost, l.GetLevel(), func() string {
      t := time.Now()
      return fmt.Sprintf(t.Format("logstash-2006.01.02"))
   })
```
To just be:
```
   elasticHook, err = elogrus.NewElasticHookWithDateFormat(
              client, elasticsearchHost, l.GetLevel(), "logstash-2006.01.02")
```

**Comment by sohlich** [comment]
That's reasonable. 
I think a lot of people will use the NewElasticHookWithFunc just to return date.

**The cleanup function purpose:**
The cleanup function is there to provide the ability to clear cached names of created indexes. From the performance perspective, it is better not to check the existence of index by each log call. So the just created names are cached in the map within the hook. The cleanup function provides the access to this map. Assuming the automatic index creation could be switched off on ES cluster.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation

See:
https://github.com/sohlich/elogrus/blob/flexible_index_name/hook.go#L135

Not sure if the solution is not "overengineered".

**Comment by sohlich** [comment]
closing due to age
